name: Compile
on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: c++ -o rock-paper-scissors main.cpp
      - name: Add to the beta folder
        run: mv rock-paper-scissors beta
      - name: Commit to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Create Beta"
          git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/rayyansaidi-com/app.git master 2>&1

