name: Beta
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: c++ -o beta/rock-paper-scissors main.cpp
      - name: Commit to GitHub
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add beta/rock-paper-scissors
          git commit -m "Create Beta"
          git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git master 
