name: Compile
on:
  workflow_dispatch:
jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove git
        run: rm -rf .git
      - name: Compile
        run: c++ -o rock-paper-scissors main.cpp
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Rock-Paper-Scissors
          path: ./*scissors
